name: Labels
on: push
jobs:
  github-metrics:
   runs-on: ubuntu-latest
   steps:
    - uses: lowlighter/metrics@latest
      with:
       filename: metrics.plugin.topics.svg
       token: NOT_NEEDED
       base: ""
       plugin_topics: yes
       plugin_topics_limit: 12
  
  
  
