name: Midly interesting facts
on: push
jobs:
  github-metrics:
   runs-on: ubuntu-latest
   steps:
    - uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.habits.facts.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_habits: yes
        plugin_habits_facts: yes
        plugin_habits_charts: no
        config_timezone: Africa/Lagos
